[project]
name = "tds-evals"
version = "0.0.0"
description = "Evaluation and fetching utilities for repo assessments"
requires-python = ">=3.12"
dependencies = [
  "typer>=0.12",
  "httpx>=0.27",
  "tqdm>=4.66",
  "pytest>=7.0",
]

[tool.pytest.ini_options]
addopts = "-q"
testpaths = ["tests"]
